### ISSUE TITLE
Warnings when running ptb_world_lm.py

### ISSUE THREAD

**Issue by rillomas** [rillomas/ai-study#1]
# general warnings
```
WARNING:tensorflow:From C:\Users\ril_l\repo\ai-study\assignment_5\reader.py:120: range_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.range(limit).shuffle(limit).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From C:\Python36\lib\site-packages\tensorflow\python\training\input.py:318: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From C:\Python36\lib\site-packages\tensorflow\python\training\input.py:188: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
WARNING:tensorflow:From C:\Python36\lib\site-packages\tensorflow\python\training\input.py:197: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From C:\Python36\lib\site-packages\tensorflow\python\training\input.py:197: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From ptb_word_lm.py:205: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
WARNING:tensorflow:From ptb_word_lm.py:504: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
```
# warning after switching to tf.train.MonitoredTraningSession
```
WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 23239 vs
 previous value: 23239. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimize
r.minimize.                                                                                                                              
```

**Comment by rillomas** [comment]
The reason of the warning `It seems that global step (tf.train.get_global_step) has not been increased...` seems to be coming from the fact that validation is also done using the same MonitoredTrainingSession.

Since MonitoredTraningSession is a session dedicated for traning this seems understandable. I probably need to move the validation/testing phase to another session

For a temporary fix, I copied from https://github.com/mozilla/DeepSpeech/issues/1505

**Comment by rillomas** [comment]
It seems the CudnnLSTM API has changed and due to that I am getting an error. This pull request seems to be dealing with the same problem https://github.com/tensorflow/models/pull/5064.

```
Traceback (most recent call last):
  File "ptb_word_lm.py", line 554, in <module>
    tf.app.run()
  File "C:\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "ptb_word_lm.py", line 486, in main
    is_training=True, config=config, input_=train_input)
  File "ptb_word_lm.py", line 135, in __init__
    output, state = self._build_rnn_graph(inputs, config, is_training)
  File "ptb_word_lm.py", line 176, in _build_rnn_graph
    return self._build_rnn_graph_cudnn(inputs, config, is_training)
  File "ptb_word_lm.py", line 187, in _build_rnn_graph_cudnn
    dropout=1 - config.keep_prob if is_training else 0)
TypeError: __init__() got an unexpected keyword argument 'input_size'
```
